# docker-compose.yml
version: '3.8'
services:
  db:
    image: postgres:14-alpine
    container_name: base-intel-db
    restart: always
    environment:
      - POSTGRES_USER=trader
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=base_mainnet
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data